### ISSUE TITLE
UUID in vendordeps JSON file does not conform to UUID standards

### ISSUE THREAD

**Issue by Javaru** [Coppersource/LibCu#4]
The `uuid` -- `libcufrc-e6e8-4db6-89f0-copperforge0` -- in the [vendordeps.json](https://github.com/Coppersource/LibCu/blob/master/vendordep.json) file does not conform to the [UUID standard](https://pubs.opengroup.org/onlinepubs/9629399/apdxa.htm#tagtcjh_34) as defined by the _Open Software Foundation_ (OSF) as part of the Distributed Computing Environment (DCE), and documented in [RFC-4122](https://www.rfc-editor.org/info/rfc4122) and [ ITU-T Rec. X.667 | ISO/IEC 9834-8:2005](https://www.itu.int/rec/T-REC-X.667-200409-S/en).

A valid UUID generator -- such as the [UUID.randomUUID()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/UUID.html#randomUUID()) method in the Java API or the online version 4 generator  at [uuidgenerator.net](https://www.uuidgenerator.net/version4) -- can be used to generate a valid version 4 UUID.

I write/maintain the [IntelliJ IDEA FRC Plugin](https://plugins.jetbrains.com/plugin/9405-frc). The Vendordeps Management feature in the plugin uses the UUID field to uniquely identify vendor library and assumes a well formed UUID.

**Comment by WardBenjamin** [comment]
To my knowledge, this is a valid UUID v4 (the first digit after the second dash is appropriately set to 4). In v4, there are no other guarantees on the other digits. Please correct me if I am wrong.

**Comment by Javaru** [comment]
Do you know where it is stated that a version 4 UUID makes no guarantees of digits (other than the version digit)?  As I read through RFC-4122, I am not seeing anything that would indicate that. The only difference for a version 4 UUID called out directly  in the spec is in how the timestamp is constructed (§4.1.4), how the clock sequence is generated (§4.1.5), and how the node is generated (§4.1.6). I am not seeing anything that indicates a version 4 UUID does not represents a 128 bit long integer value as the other versions do. In other words, version 4 is just a change in the algorithm used to generate the 128 bit value. And as I read §3 which covers the String Representation of a UUID, I am not seeing anything in it that indicates non hex characters are allowed when representing that 128 bit long:

> ### Declaration of syntactic structure:
> A UUID is an identifier that is unique across both space and time, with respect to the space of all UUIDs.  Since a UUID is a fixed size and contains a time field, it is possible for values to rollover (around A.D. 3400, depending on the specific algorithm used).  A UUID can be used for multiple purposes, from tagging objects with an extremely short lifetime, to reliably identifying very persistent objects across a network.
> 
> The internal representation of a UUID is a specific sequence of bits in memory, as described in Section 4.  To accurately represent a UUID as a URN, it is necessary to convert the bit sequence to a string representation.
> 
> _**Each field is treated as an integer and has its value printed as a zero-filled hexadecimal digit string**_ with the most significant digit first.  The hexadecimal values "a" through "f" are output as lower case characters and are case insensitive on input.
> 
> The formal definition of the UUID string representation is provided by the following extended BNF:
>
> ``` 
> UUID                   = <time_low> <hyphen> <time_mid> <hyphen>
>                          <time_high_and_version> <hyphen> 
>                          <clock_seq_and_reserved>
>                          <clock_seq_low> <hyphen> <node>
> time_low               = <hexOctet> <hexOctet> <hexOctet> <hexOctet>
> time_mid               = <hexOctet> <hexOctet>
> time_high_and_version  = <hexOctet> <hexOctet>
> clock_seq_and_reserved = <hexOctet>
> clock_seq_low          = <hexOctet>
> node                   = <hexOctet><hexOctet><hexOctet>
 >                        <hexOctet><hexOctet><hexOctet>
> hexOctet               = <hexDigit> <hexDigit>
> hexDigit               = <digit> | <a> | <b> | <c> | <d> | <e> | <f>
> digit                  = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
>                          "8" | "9"
> hyphen                 = "-"
> a                      = "a" | "A"
> b                      = "b" | "B"
> c                      = "c" | "C"
> d                      = "d" | "D"
> e                      = "e" | "E"
> f                      = "f" | "F"
> ```

That's my understanding of the specification. And that understanding seems to be confirmed in this [Stackoverflow discussion](https://stackoverflow.com/questions/8258480/type-of-character-generated-by-uuid) on UUIDs.

Also, since the Java API supports version 4 UUIDs, I would not expect an error when parsing the provided UUID. But when parsing the LibCu UUID, an exception is thrown:
```
import java.util.UUID;

public static void main(String[] args)
{
    UUID uuid = UUID.fromString("libcufrc-e6e8-4db6-89f0-copperforge0");
    System.out.println(uuid);
}

-------

Exception in thread "main" java.lang.NumberFormatException: Error at index 0 in: "libcufrc"
	at java.base/java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:84)
	at java.base/java.lang.Long.parseLong(Long.java:790)
	at java.base/java.util.UUID.fromString1(UUID.java:283)
	at java.base/java.util.UUID.fromString(UUID.java:258)
	at wb.general.kotlin.io.KotlinWalkFileTreeKt.main(KotlinWalkFileTree.kt:18)
	at wb.general.kotlin.io.KotlinWalkFileTreeKt.main(KotlinWalkFileTree.kt)
```

Same for Python:
```
import uuid

print(uuid.UUID("libcufrc-e6e8-4db6-89f0-copperforge0"))

------

Traceback (most recent call last):
  File " C:\dev\scripts\uuid_test.py", line 3, in <module>
    print(uuid.UUID("libcufrc-e6e8-4db6-89f0-copperforge0"))
  File "C:\dev\sdk\python\Python38\lib\uuid.py", line 170, in __init__
    int = int_(hex, 16)
ValueError: invalid literal for int() with base 16: 'libcufrce6e84db689f0copperforge0'

```

**Comment by WardBenjamin** [comment]
@Javaru I updated the UUID to a valid value. The 2022 vendordeps will be published with the new value shortly.
